#mysql data base configs

development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stocks_app_development
  pool: 5
  username: root
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stocks_app_test
  pool: 5
  username: root
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: stocks_app_production
  pool: 5
  username: root
  socket: /tmp/mysql.sock